# Generated by Django 6.0.3 on 2026-04-08 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_shopkeeper_groups_shopkeeper_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopkeeper',
            name='address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
